### DISCUSSION TITLE
How do I generate the appOfApps file?

### DISCUSSION THREAD

**Discussion by liyangau** [arnarg/nixidy#22] [Q&A]
Hi,

Following the guide, it can generate applications with their YAML files successfully but I am not too sure how to generate this appOfApps application.

Do we create this file manually as below?
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appOfApps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./manifests/dev/apps
    repoURL: git@github.com:xxx/argocd.git
    targetRevision: main
```
